In [1]:
from deeplab2.model.pixel_encoder import moat
import tensorflow as tf
import numpy as np


In [96]:
ourmodel=moat.get_model(
    name='tiny_moat0_pretrain_256_no_pe_1k',input_shape=[256,256,3])

In [18]:
ourmodel.summary()

Model: "moat"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 stem (Sequential)           (None, 1, 1, 32)          9696      
                                                                 
 block_00_00 (MBConvBlock)   multiple                  12712     
                                                                 
 block_00_01 (MBConvBlock)   multiple                  12712     
                                                                 
 block_01_00 (MBConvBlock)   multiple                  39696     
                                                                 
 block_01_01 (MBConvBlock)   multiple                  45904     
                                                                 
 block_01_02 (MBConvBlock)   multiple                  45904     
                                                                 
 block_02_00 (MOATBlock)     multiple                  182016 

In [22]:
hidden_2 = ourmodel.layers[2]
hidden_2.get_weights()

[array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32),
 array([[[[-0.00068617, -0.00440142,  0.03888358, ..., -0.00992546,
            0.01525975,  0.00200797],
          [ 0.01443597, -0.00384924,  0.01279211, ..., -0.01978549,
           -0.02390736, -0.0059576 ],
          [-0.01631959, -0.01485646,  0.00261135, ..., -0.00238973,
            0.01617188,  0.02407456],
          ...,
          [-0.00735315, -0.01420683, -0.00316908, ..., -0.00855356,
            0.02001322, -0.00064186],
          [-0.00797974,  0.00409764, -0.00258956, ..., -0.01759086,
           -0.02206425,  0.03614211],
          [ 0.0338296 , -0.01083712,  0.0023725 , ..., -0.01781806,
           -0.00852687,  0.01567768]]]], dtype=floa

In [159]:
ourmodel = moat._load_moat_pretrained_checkpoint(ourmodel, path="./model-ckpt-0")
hidden_2 = ourmodel.layers[2]
hidden_2.get_weights()

[array([0.8721897 , 0.30142564, 0.85832554, 1.282949  , 0.9317156 ,
        0.8322677 , 0.6199395 , 0.9125377 , 0.9394865 , 1.031087  ,
        0.82400197, 0.8123415 , 1.1977469 , 0.8521327 , 0.8133826 ,
        0.6739886 , 0.85744894, 0.9288123 , 0.9711221 , 0.9539995 ,
        0.8782829 , 0.7687977 , 0.60772794, 0.7258682 , 1.4746784 ,
        0.762828  , 0.8450476 , 1.4259994 , 1.0115973 , 0.63408923,
        0.85444343, 3.4550712 ], dtype=float32),
 array([ 0.2874648 ,  0.39785114,  0.10863896,  0.73331195,  0.90103817,
        -0.80956584,  0.19962467, -0.9641612 , -0.4588957 ,  0.11874445,
        -0.06640941, -0.85102546,  0.26781657, -0.6158939 ,  0.04129916,
        -0.4309165 , -0.22831813,  0.4158675 ,  0.3960928 , -0.866772  ,
        -0.01549559, -0.8487544 , -0.39282545, -0.9781697 , -0.0475563 ,
        -0.20766035,  0.7218953 , -1.5674189 , -0.74631786,  0.09056404,
         0.2698607 , -0.46579644], dtype=float32),
 array([[[[-0.05365658,  0.0127856 , -0.01222573, ...,

In [6]:
from keras.layers import Input, Dense
from keras.models import Model

In [97]:
ourmodel.input_shape

(None, 256, 256, 3)

In [98]:
ourmodel.output_shape

{'stage1': (None, 128, 128, 32),
 'res1': (None, 128, 128, 32),
 'stage2': (None, 64, 64, 32),
 'res2': (None, 64, 64, 32),
 'stage3': (None, 32, 32, 64),
 'res3': (None, 32, 32, 64),
 'stage4': (None, 16, 16, 128),
 'res4': (None, 16, 16, 128),
 'stage5': (None, 8, 8, 256),
 'res5': (None, 8, 8, 256)}

In [ ]:
#아웃풋이 텐서 10개... 개빡친다 -> 커스텀 레이어를 정의해야함...
#잘 모르니까 가내수공업으로

In [ ]:
###functional API로! 
### 아웃풋 출력 확인
### 확인할거 -> 웨이트 저장법이랑 저장 잘 되는지.

In [172]:
y11 = tf.keras.layers.Flatten(name='flatten_layer11')(ourmodel.output["stage1"])
y12 = tf.keras.layers.Flatten(name='flatten_layer12')(ourmodel.output["res1"])
y21 = tf.keras.layers.Flatten(name='flatten_layer21')(ourmodel.output["stage2"])
y22 = tf.keras.layers.Flatten(name='flatten_layer22')(ourmodel.output["res2"])
y31 = tf.keras.layers.Flatten(name='flatten_layer31')(ourmodel.output["stage3"])
y32 = tf.keras.layers.Flatten(name='flatten_layer32')(ourmodel.output["res3"])
y41 = tf.keras.layers.Flatten(name='flatten_layer41')(ourmodel.output["stage4"])
y42 = tf.keras.layers.Flatten(name='flatten_layer42')(ourmodel.output["res4"])
y51 = tf.keras.layers.Flatten(name='flatten_layer51')(ourmodel.output["stage5"])
y52 = tf.keras.layers.Flatten(name='flatten_layer52')(ourmodel.output["res5"])

In [173]:
z1 = y11+y12
z2 = y21+y22
z3 = y31+y32
z4 = y41+y42
z5 = y51+y52
v =tf.concat([y1,z2,z3,z4,z5],axis=1)
output_layer = tf.keras.layers.Dense(
    units=101, activation='softmax', name='output_layer')(v)





In [174]:
model = tf.keras.models.Model(ourmodel.input, output_layer)
model.summary()

Model: "model_9"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_3 (InputLayer)           [(None, 256, 256, 3  0           []                               
                                )]                                                                
                                                                                                  
 moat (MOAT)                    {'stage1': (None, 1  3104288     ['input_3[0][0]']                
                                28, 128, 32),                                                     
                                 'res1': (None, 128                                               
                                , 128, 32),                                                       
                                 'stage2': (None, 6                                         

In [ ]:
### 단순히 그냥 5개의 결과+스킵커넥션을 flatten해서 FC 층 만들었더니
### 파라미터 수가 정신나감
### 구글에서 어떻게 만들었는지 보고싶은데 못보네
### 배경지식이 없어서...
### Convolution 등등의 층 붙여서 파라미터 수 줄여야될듯